# Generated by Django 5.2.7 on 2025-11-08 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_booking', '0002_alter_sessionbooking_enrollment_tastersession'),
        ('coaching_core', '0001_initial'),
        ('payments', '0002_order_guest_order_token_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coaching_booking.clientofferingenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching_core.offering')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.coachingorder')),
            ],
        ),
    ]
