# Generated by Django 4.2.7 on 2025-12-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_coachingorder_coachingorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='printful_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='printful_order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
