# Generated by Django 5.2.7 on 2025-12-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
