# Generated by Django 5.2.7 on 2025-12-09 09:58

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_core', '0003_offering_coach_revenue_share_and_more'),
        ('dreamers', '0003_dreamerprofile_payout_details_dreamerprofile_slug_and_more'),
        ('payments', '0008_order_carrier_order_tracking_number_and_more'),
        ('products', '0008_variant_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingorder',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='coachingorder',
            name='amount_coach',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Owed to Coach', max_digits=10),
        ),
        migrations.AddField(
            model_name='coachingorder',
            name='amount_company',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Retained by JH Motiv', max_digits=10),
        ),
        migrations.AddField(
            model_name='coachingorder',
            name='amount_gross',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total paid by client', max_digits=10),
        ),
        migrations.AddField(
            model_name='coachingorder',
            name='amount_referrer',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Owed to Dreamer', max_digits=10),
        ),
        migrations.AddField(
            model_name='coachingorder',
            name='payout_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('void', 'Void')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='coachingorder',
            name='referrer',
            field=models.ForeignKey(blank=True, help_text='The Dreamer who referred this sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dreamers.dreamerprofile'),
        ),
        migrations.AddField(
            model_name='coachingorder',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID for idempotency.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code_snapshot',
            field=models.CharField(blank=True, help_text='The code used (e.g. SUMMER20)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_data_snapshot',
            field=models.JSONField(blank=True, help_text="A snapshot of the coupon's rules at time of purchase.", null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID for idempotency.', max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='e.g., 10.00 for fixed amount, or 15 for 15%', max_digits=10)),
                ('coupon_type', models.CharField(choices=[('discount', 'Discount (Reduces subtotal, affects tax)'), ('gift_card', 'Gift Card (Acts as payment, reduces grand total)')], default='discount', max_length=10)),
                ('free_shipping', models.BooleanField(default=False)),
                ('limit_to_product_type', models.CharField(choices=[('all', 'All Products & Coaching'), ('physical', 'Physical Products Only'), ('coaching', 'Coaching Only')], default='all', max_length=20)),
                ('min_cart_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total times this code can be used.', null=True)),
                ('one_per_customer', models.BooleanField(default=False, help_text='Limit to one use per customer.')),
                ('new_customers_only', models.BooleanField(default=False, help_text="Can only be used on a customer's first order.")),
                ('affiliate_dreamer', models.ForeignKey(blank=True, help_text='Link this coupon to a Dreamer for affiliate tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='dreamers.dreamerprofile')),
                ('referrer', models.ForeignKey(blank=True, help_text="The user who 'owns' this coupon (for affiliate tracking).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_coupons', to=settings.AUTH_USER_MODEL)),
                ('specific_offerings', models.ManyToManyField(blank=True, help_text='Applies only to these coaching packages.', to='coaching_core.offering')),
                ('specific_products', models.ManyToManyField(blank=True, help_text='Applies only to these products.', to='products.product')),
                ('user_specific', models.ForeignKey(blank=True, help_text='If set, only this user can use this coupon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.coupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
