# Generated by Django 5.2.7 on 2025-12-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailresendlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated for the browser view version', unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Schedule for future sending', null=True)),
                ('template', models.CharField(choices=[('standard', 'Standard (Text Focused)'), ('hero', 'Visual Impact (Big Image)'), ('showcase', 'Product Showcase (Grid)')], default='standard', max_length=20)),
                ('header_image', models.ImageField(blank=True, help_text='Top banner image (Recommended for Hero/Showcase layouts)', null=True, upload_to='newsletters/')),
                ('body', models.TextField(help_text='Main content. HTML is supported.')),
                ('cta_text', models.CharField(blank=True, help_text="E.g. 'Shop the Collection'", max_length=50, verbose_name='Button Text')),
                ('cta_link', models.URLField(blank=True, verbose_name='Button Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
