# Generated by Django 5.2.7 on 2025-12-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='template',
            field=models.CharField(choices=[('standard', 'Standard (Text Focused)'), ('hero', 'Visual Impact (Big Image)'), ('showcase', 'Product Showcase (Grid)')], default='standard', max_length=20),
        ),
    ]
