# Generated by Django 5.2.7 on 2025-12-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newslettercampaign_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image for Hero layouts', null=True, upload_to='campaigns/'),
        ),
    ]
