# Generated by Django 5.2.7 on 2025-11-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_is_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='The start date of the vacation period.', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='The end date of the vacation period.', verbose_name='End Date')),
                ('cancel_bookings', models.BooleanField(default=True, help_text='If checked, all bookings within this vacation period will be automatically cancelled.', verbose_name='Cancel Existing Bookings')),
                ('coach', models.ForeignKey(help_text='The coach taking the vacation.', on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='accounts.coachprofile', verbose_name='Coach')),
            ],
            options={
                'verbose_name': 'Coach Vacation',
                'verbose_name_plural': 'Coach Vacations',
                'ordering': ['coach', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='CoachAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='The day of the week for this availability slot.', verbose_name='Day of the Week')),
                ('start_time', models.TimeField(help_text='The start time of the availability slot.', verbose_name='Start Time')),
                ('end_time', models.TimeField(help_text='The end time of the availability slot.', verbose_name='End Time')),
                ('coach', models.ForeignKey(help_text='The coach to whom this availability belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.coachprofile', verbose_name='Coach')),
            ],
            options={
                'verbose_name': 'Coach Availability',
                'verbose_name_plural': 'Coach Availabilities',
                'ordering': ['coach', 'day_of_week', 'start_time'],
                'unique_together': {('coach', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
