# Generated by Django 5.2.7 on 2025-11-30 14:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_availability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachavailability',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coachvacation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='coachavailability',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coachvacation',
            name='cancel_bookings',
        ),
        migrations.AddField(
            model_name='coachvacation',
            name='existing_booking_handling',
            field=models.CharField(choices=[('keep', 'Keep'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel')], default='reschedule', max_length=10),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='day_of_week',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='coachvacation',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachvacation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coachvacation',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='DateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coach', 'date')},
            },
        ),
    ]
