# Generated by Django 5.2.7 on 2025-11-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_availability', '0003_alter_coachavailability_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachavailability',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
    ]
