# Generated by Django 5.2.7 on 2025-10-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Job title or role (e.g., Founder & CEO, Lead Coach).', max_length=150)),
                ('bio', models.TextField(help_text='A brief description or biography of the team member.')),
                ('profile_image', models.ImageField(help_text='Upload a professional photo for the team member.', upload_to='team_photos/')),
                ('is_active', models.BooleanField(default=True, help_text='Display on the Meet the Team page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual ordering for display.')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
