# Generated by Django 5.2.7 on 2025-12-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='character_class',
            field=models.CharField(choices=[('GAME_MASTER', 'Game Master (Founder/Jack of All Trades)'), ('PALADIN', 'Paladin (Leader/Tank)'), ('ROGUE', 'Rogue (Agility/Sales)'), ('MAGE', 'Mage (Specialist/Strategy)'), ('BARD', 'Bard (Community/Marketing)'), ('HEALER', 'Healer (Coach/Support)'), ('WARRIOR', 'Warrior (Operations/Grind)'), ('TECHNOMANCER', 'Technomancer (Dev/Tech)'), ('NPC', 'NPC (Guest/Other)')], default='WARRIOR', help_text='Determines the color ring and icon on the About page.', max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(help_text='A brief description or biography.'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text='Job title (e.g., Founder, Lead Coach).', max_length=150),
        ),
    ]
