# Generated by Django 5.2.7 on 2025-11-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_is_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The Offering's Name/Title.", max_length=255)),
                ('slug', models.SlugField(editable=False, help_text='Unique slug for URL purposes, auto-generated from name.', unique=True)),
                ('description', models.TextField(help_text='Description of the offering.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost of the package/service.', max_digits=10)),
                ('duration_type', models.CharField(choices=[('WEEK', 'Week'), ('MONTH', 'Month'), ('PACKAGE', 'Package')], help_text='Duration measurement (e.g., Week, Month).', max_length=10)),
                ('total_length_units', models.IntegerField(help_text='e.g., 4 for 4 weeks or 3 for 3 months.')),
                ('session_length_minutes', models.IntegerField(help_text='Length of each session in minutes (e.g., 60, 90).')),
                ('total_number_of_sessions', models.IntegerField(help_text='The initial session count for a client package.')),
                ('is_whole_day', models.BooleanField(default=False, help_text='For offerings where times are set ad-hoc, bypassing fixed availability.')),
                ('active_status', models.BooleanField(default=False, help_text='Is the offering currently active? Auto-set based on assigned coaches.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coaches', models.ManyToManyField(blank=True, help_text='Coaches who can fulfill this offering.', related_name='offerings', to='accounts.coachprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coaching Offering',
                'verbose_name_plural': 'Coaching Offerings',
                'ordering': ['name'],
            },
        ),
    ]
