# Generated by Django 5.2.7 on 2025-11-30 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_configure_social_app'),
        ('coaching_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The Workshop's Name/Title.", max_length=255)),
                ('slug', models.SlugField(editable=False, help_text='Unique slug for URL purposes, auto-generated from name.', unique=True)),
                ('description', models.TextField(help_text='Detailed description of the workshop.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost for attending the workshop.', max_digits=10)),
                ('date', models.DateField(help_text='The date of the workshop.')),
                ('start_time', models.TimeField(help_text='The start time of the workshop.')),
                ('end_time', models.TimeField(help_text='The end time of the workshop.')),
                ('total_attendees', models.IntegerField(help_text='Maximum number of attendees allowed.')),
                ('is_free', models.BooleanField(default=False, help_text='Is this a free workshop?')),
                ('active_status', models.BooleanField(default=True, help_text='Is the workshop currently active and bookable?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, help_text='Users who have booked this workshop.', related_name='attended_workshops', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(help_text='The coach hosting the workshop.', on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='accounts.coachprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
