# Generated by Django 5.2.7 on 2025-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_core', '0002_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='coach_revenue_share',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Percentage of the final sale price that goes to the Coach (e.g. 70.00).', max_digits=5),
        ),
        migrations.AddField(
            model_name='offering',
            name='referral_commission_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed Amount')], default='percent', max_length=10),
        ),
        migrations.AddField(
            model_name='offering',
            name='referral_commission_value',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Finder's fee for the Dreamer/Affiliate (e.g. 10% or £50).", max_digits=10),
        ),
    ]
