# Generated by Django 5.2.7 on 2025-12-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_core', '0003_offering_coach_revenue_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='gcal_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Calendar Event ID'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link for virtual workshops (e.g. Zoom, Google Meet).', verbose_name='Virtual Meeting Link'),
        ),
    ]
