# Generated by Django 5.2.7 on 2025-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_guest_alter_user_email'),
        ('coaching_core', '0004_workshop_gcal_event_id_workshop_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='coaches',
            field=models.ManyToManyField(help_text='The coaches who can provide this offering.', limit_choices_to={'user__is_coach': True}, related_name='offerings', to='accounts.coachprofile'),
        ),
    ]
