# Generated by Django 5.2.7 on 2026-01-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_core', '0005_alter_offering_coaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='slug',
            field=models.SlugField(editable=False, help_text='Unique slug for URL purposes, auto-generated from name.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='slug',
            field=models.SlugField(editable=False, help_text='Unique slug for URL purposes, auto-generated from name.', max_length=255, unique=True),
        ),
    ]
