# Generated by Django 5.2.7 on 2025-10-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DreamerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name or Business Name (e.g., Ashley Johnson | Haijahr)', max_length=150)),
                ('story_excerpt', models.TextField(blank=True, help_text='A short paragraph about their journey or dream.')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature this dreamer prominently.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual ordering for display on the site.')),
            ],
            options={
                'verbose_name': 'Dreamer Profile',
                'verbose_name_plural': 'Dreamer Profiles',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('website', 'Website/Personal Link'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('spotify', 'Spotify'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('twitter', 'X (Twitter)'), ('github', 'GitHub'), ('etsy', 'Etsy'), ('email', 'Email Address (Mailto)')], help_text='Type of social media or link.', max_length=50)),
                ('url', models.URLField(help_text='Full URL to their profile or website (or mailto: link).', max_length=300)),
                ('dreamer', models.ForeignKey(help_text='The Dreamer this link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='dreamers.dreamerprofile')),
            ],
            options={
                'verbose_name': 'Channel Link',
                'verbose_name_plural': 'Channel Links',
                'ordering': ['dreamer', 'channel_type'],
            },
        ),
    ]
