# Generated by Django 5.2.7 on 2025-12-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dreamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
