# Generated by Django 5.2.7 on 2025-12-09 09:58

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamers', '0002_dreamer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamerprofile',
            name='payout_details',
            field=accounts.fields.CustomEncryptedJSONField(blank=True, help_text="Encrypted JSON: {'bank_name': '...', 'sort_code': '...', 'account_number': '...'}", null=True),
        ),
        migrations.AddField(
            model_name='dreamerprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier. Auto-generated from name if left blank.', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='dreamerprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link this profile to a user account to enable the Affiliate Dashboard.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dreamer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
