# Generated by Django 5.2.7 on 2025-12-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamers', '0003_dreamerprofile_payout_details_dreamerprofile_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dreamerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Application Pending'), ('approved', 'Approved Affiliate'), ('rejected', 'Application Rejected')], default='pending', max_length=20),
        ),
    ]
