# Generated by Django 5.2.7 on 2025-12-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamers', '0004_dreamerprofile_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('website', 'Website/Personal Link'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('spotify', 'Spotify'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('twitter', 'X (Twitter)'), ('github', 'GitHub'), ('etsy', 'Etsy'), ('email', 'Email Address (Mailto)')], help_text='Type of social media or link.', max_length=50)),
                ('url', models.URLField(help_text='Full URL to their profile or website (or mailto: link).', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('dreamer', models.ForeignKey(help_text='The Dreamer this link belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='dreamers.dreamerprofile')),
            ],
            options={
                'verbose_name': 'Dreamer Channel',
                'verbose_name_plural': 'Dreamer Channels',
                'ordering': ['dreamer', 'channel_type'],
            },
        ),
        migrations.DeleteModel(
            name='ChannelLink',
        ),
    ]
