# Generated by Django 5.2.7 on 2025-11-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='A unique slug for clean URLs.', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Main body text, studies, coaching comparisons, etc.', verbose_name='Content')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('downloadable_file', models.FileField(blank=True, help_text='Optional mini workbook or other downloadable material.', null=True, upload_to='workbooks/', verbose_name='Downloadable File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Page',
                'verbose_name_plural': 'Content Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Link Title')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('content_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='coaching_client.contentpage', verbose_name='Content Page')),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
            },
        ),
        migrations.CreateModel(
            name='TasterSessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10, verbose_name='Status')),
                ('decision_at', models.DateTimeField(blank=True, null=True, verbose_name='Decision At')),
                ('notes', models.TextField(blank=True, help_text='Notes for why the request was approved or denied.', verbose_name='Internal Notes')),
                ('approver', models.ForeignKey(blank=True, help_text='The staff member who approved or denied the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasters', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taster_session_request', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Taster Session Request',
                'verbose_name_plural': 'Taster Session Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
