# Generated by Django 5.2.7 on 2025-12-03 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_client', '0002_alter_tastersessionrequest_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tastersessionrequest',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='tastersessionrequest',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='tastersessionrequest',
            name='goal_summary',
            field=models.TextField(default='', verbose_name='Goal Summary'),
        ),
        migrations.AddField(
            model_name='tastersessionrequest',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='tastersessionrequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taster_session_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
