# Generated by Django 5.2.7 on 2025-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_client', '0003_tastersessionrequest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tastersessionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
