# Generated by Django 5.2.7 on 2025-12-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_client', '0004_alter_tastersessionrequest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasterSessionRequest',
        ),
    ]
