# Generated by Django 5.2.7 on 2025-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistic', models.CharField(help_text="The core statistic, e.g., '70%' or '7x'.", max_length=50)),
                ('description', models.TextField(help_text='The descriptive text accompanying the statistic.')),
                ('source_name', models.CharField(help_text="The name of the source of the fact, e.g., 'ICF Global Coaching Study'.", max_length=200)),
                ('source_link', models.URLField(help_text='A URL to the source for verification.', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this fact should be displayed on the site.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='The order in which to display the facts (lowest first).')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
