# Generated by Django 5.2.7 on 2025-12-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={},
        ),
        migrations.RemoveField(
            model_name='fact',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='order',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='statistic',
        ),
        migrations.AddField(
            model_name='fact',
            name='brief_fact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
