# Generated by Django 5.2.7 on 2025-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_alter_fact_options_remove_fact_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fact',
            old_name='link',
            new_name='source_link',
        ),
        migrations.RenameField(
            model_name='fact',
            old_name='brief_fact',
            new_name='statistic_description',
        ),
        migrations.AddField(
            model_name='fact',
            name='source_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
