# Generated by Django 5.2.7 on 2025-11-01 22:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('USER', 'User'), ('COACH', 'Coach')], max_length=10)),
                ('hours_before_session', models.PositiveIntegerField()),
                ('refund_percentage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_out', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sessions', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='coaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Public-facing service name.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=255)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes (e.g., 60 or 90).')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price for this offering.', max_digits=8)),
                ('credits_granted', models.PositiveIntegerField(default=1, help_text='Number of session credits granted upon purchase.')),
                ('duration_months', models.PositiveIntegerField(default=3, help_text='How many months of access this program grants.')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the public site.')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='The amount the coach will be paid for this offering.', max_digits=8, null=True)),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach Offering',
                'verbose_name_plural': 'Coach Offerings',
                'unique_together': {('coach', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CoachPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_COACH', 'Pending Coach Approval'), ('PENDING_USER', 'Pending User Approval'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING_COACH', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiating_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_swap_requests', to=settings.AUTH_USER_MODEL)),
                ('receiving_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swap_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swap_request', to='coaching.coachingsession')),
            ],
        ),
        migrations.CreateModel(
            name='CoachVacationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('override_allowed', models.BooleanField(default=False, help_text='If True, the coach can choose to book sessions during this block.')),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vacation_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacation/Unbookable Block',
                'verbose_name_plural': 'Vacation/Unbookable Blocks',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_request', to='coaching.coachingsession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='coaching.coachingsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='The last day the user can book sessions under this offering.')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_enrollments', to='coaching.coachoffering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taster', models.BooleanField(default=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_credit', to='coaching.coachingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_credits', to=settings.AUTH_USER_MODEL)),
                ('user_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_credits', to='coaching.useroffering')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='coaching.useroffering')),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taster', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Pending Review'), ('A', 'Approved - Credit Granted'), ('D', 'Denied')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('denied_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_applications', to=settings.AUTH_USER_MODEL)),
                ('denied_by', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denied_credit_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Application',
                'verbose_name_plural': 'Credit Applications',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_taster', True), ('status__in', ['P', 'A'])), fields=('user', 'is_taster'), name='unique_pending_or_approved_taster')],
            },
        ),
        migrations.CreateModel(
            name='RecurringAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday to 6=Sunday).')),
                ('start_time', models.TimeField(help_text="Start time for this day's availability.")),
                ('end_time', models.TimeField(help_text="End time for this day's availability.")),
                ('is_available', models.BooleanField(default=True, help_text='If set to False, the coach is unavailable for the entire day.')),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Availability Block',
                'verbose_name_plural': 'Recurring Availability Blocks',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('coach', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='SpecificAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The specific day this availability applies to.')),
                ('start_time', models.TimeField(help_text='Start time for this specific slot.')),
                ('end_time', models.TimeField(help_text='End time for this specific slot.')),
                ('is_available', models.BooleanField(default=True, help_text='If True, this slot is available; if False, this slot is explicitly blocked (one-off block).')),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='specific_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specific Availability Slot',
                'verbose_name_plural': 'Specific Availability Slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('coach', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
