# Generated by Django 5.2.7 on 2025-11-01 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coachoffering',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='coachoffering',
            name='coaches',
            field=models.ManyToManyField(limit_choices_to={'is_coach': True}, related_name='offerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='coachoffering',
            name='coach',
        ),
    ]
