# Generated by Django 5.2.7 on 2025-10-30 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coachingsession_end_time_coachingsession_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachVacationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='vacation_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacation/Unbookable Block',
                'verbose_name_plural': 'Vacation/Unbookable Blocks',
                'ordering': ['start_date'],
            },
        ),
        migrations.DeleteModel(
            name='CoachCalendarCredentials',
        ),
    ]
