# Generated by Django 5.2.7 on 2025-11-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_alter_coachoffering_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingsession',
            name='service_name',
        ),
        migrations.AddField(
            model_name='coachingsession',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='coaching.coachoffering'),
        ),
        migrations.AlterField(
            model_name='coachingsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='coachoffering',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier. Auto-generated if left blank.', max_length=255),
        ),
    ]
