# Generated by Django 5.2.7 on 2025-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_remove_coachingsession_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingsession',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Automatically calculated on save.'),
        ),
    ]
