# Generated by Django 5.2.7 on 2025-10-30 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_coachvacationblock_delete_coachcalendarcredentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Public-facing service name.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=255)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes (e.g., 60 or 90).')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility on the public site.')),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach Offering',
                'verbose_name_plural': 'Coach Offerings',
                'unique_together': {('coach', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RecurringAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday to 6=Sunday).')),
                ('start_time', models.TimeField(help_text="Start time for this day's availability.")),
                ('end_time', models.TimeField(help_text="End time for this day's availability.")),
                ('is_available', models.BooleanField(default=True, help_text='If set to False, the coach is unavailable for the entire day.')),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Availability Block',
                'verbose_name_plural': 'Recurring Availability Blocks',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('coach', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='SpecificAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The specific day this availability applies to.')),
                ('start_time', models.TimeField(help_text='Start time for this specific slot.')),
                ('end_time', models.TimeField(help_text='End time for this specific slot.')),
                ('is_available', models.BooleanField(default=True, help_text='If True, this slot is available; if False, this slot is explicitly blocked (one-off block).')),
                ('coach', models.ForeignKey(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='specific_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Specific Availability Slot',
                'verbose_name_plural': 'Specific Availability Slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('coach', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
