# Generated by Django 5.2.7 on 2025-11-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_alter_coachingsession_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachoffering',
            name='is_full_day',
            field=models.BooleanField(default=False, help_text='Check if this is a full-day session that blocks the entire day.'),
        ),
        migrations.AddField(
            model_name='coachoffering',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Optional: Any specific terms and conditions for this offering.'),
        ),
        migrations.AlterField(
            model_name='coachoffering',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes (e.g., 60). Leave blank for full-day sessions.', null=True),
        ),
        migrations.CreateModel(
            name='PreSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="The question text (e.g., 'What is your primary goal for this session?')", max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the questions are displayed.')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_session_questions', to='coaching.coachoffering')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
