# Generated by Django 5.2.7 on 2025-10-30 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_coachoffering_recurringavailability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recurringavailability',
            unique_together={('coach', 'day_of_week')},
        ),
    ]
