# Generated by Django 5.2.7 on 2025-10-30 19:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_alter_recurringavailability_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveIntegerField(help_text='How many months of access this program grants.')),
                ('tokens_granted', models.PositiveIntegerField(help_text='Number of session tokens granted upon purchase.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this program is available for purchase.')),
            ],
        ),
        migrations.AddField(
            model_name='coachoffering',
            name='booking_type',
            field=models.CharField(choices=[('token', 'Token-based'), ('price', 'Direct Price')], default='token', help_text='Determines if this session is booked with tokens or a direct price.', max_length=10),
        ),
        migrations.AddField(
            model_name='coachoffering',
            name='tokens_required',
            field=models.PositiveIntegerField(default=1, help_text='Number of tokens required to book this session (if token-based).'),
        ),
        migrations.AlterField(
            model_name='coachoffering',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Required only if booking_type is 'Direct Price'.", max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text='The last day the user can book sessions under this program.')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_enrollments', to='coaching.coachingprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_token', to='coaching.coachingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
                ('user_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='coaching.userprogram')),
            ],
        ),
    ]
