# Generated by Django 5.2.7 on 2025-11-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_coachoffering_is_full_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recurringavailability',
            unique_together=set(),
        ),
    ]
