# Generated by Django 5.2.7 on 2025-11-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0006_alter_recurringavailability_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringavailability',
            name='is_available',
        ),
    ]
