# Generated by Django 5.2.7 on 2025-10-31 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0007_coachprogramlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_taster',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='user_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='coaching.userprogram'),
        ),
        migrations.CreateModel(
            name='TokenApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taster', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Pending Review'), ('A', 'Approved - Token Granted'), ('D', 'Denied')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('denied_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('denied_by', models.ForeignKey(blank=True, limit_choices_to={'is_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denied_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Application',
                'verbose_name_plural': 'Token Applications',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_taster', True), ('status__in', ['P', 'A'])), fields=('user', 'is_taster'), name='unique_pending_or_approved_taster')],
            },
        ),
    ]
