# Generated by Django 5.2.7 on 2025-11-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Designates whether this user is a client.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_coach',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a coaching staff member.'),
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text="A short bio describing the coach's style and background.")),
                ('phone_number', models.CharField(blank=True, help_text="Coach's contact phone number.", max_length=20, null=True)),
                ('time_zone', models.CharField(default='UTC', help_text="The coach's local time zone for accurate scheduling conversions.", max_length=50)),
                ('public_photo', models.ImageField(blank=True, help_text='Optional public profile photo for the coach.', null=True, upload_to='coach_photos/')),
                ('is_available_for_new_clients', models.BooleanField(default=True, help_text='Allows staff to quickly block new enrollments to this coach.')),
                ('user', models.OneToOneField(limit_choices_to={'is_coach': True}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
