# Generated by Django 5.2.7 on 2025-12-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_configure_social_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='subscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
