# Generated by Django 5.2.7 on 2025-10-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_billing_notes_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_calendar_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
