# Generated by Django 5.2.7 on 2025-10-30 12:10

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_google_calendar_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_vacation',
            field=models.BooleanField(default=False, help_text='If checked, the coach is immediately unbookable.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_calendar_credentials',
            field=accounts.fields.CustomEncryptedJSONField(blank=True, null=True),
        ),
    ]
