# Generated by Django 5.2.7 on 2025-12-09 09:58

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_marketingpreference_subscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='payout_details',
            field=accounts.fields.CustomEncryptedJSONField(blank=True, help_text="Encrypted JSON: {'bank_name': '...', 'sort_code': '...', 'account_number': '...'}", null=True),
        ),
    ]
