# Generated by Django 5.2.7 on 2025-10-30 13:01

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_on_vacation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC', help_text="User's preferred time zone for display and defining working hours."),
        ),
    ]
