# Generated by Django 5.2.7 on 2025-12-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_coachprofile_payout_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='The ID of this user in Stripe (e.g. cus_12345).', max_length=255, null=True),
        ),
    ]
