# Generated by Django 5.2.7 on 2025-12-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='last_synced',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful Google Calendar sync.', null=True),
        ),
    ]
