# Generated by Django 5.2.7 on 2025-12-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_coachprofile_last_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dreamer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is an approved Dreamer affiliate.'),
        ),
    ]
