# Generated by Django 5.2.7 on 2025-12-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_dreamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_invite_sent',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the last guest invite was sent.', null=True),
        ),
    ]
