# Generated by Django 5.2.7 on 2025-11-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_is_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(help_text="The ID of the specific calendar used for bookings (e.g., 'primary').", max_length=255, verbose_name='Google Calendar ID')),
                ('access_token', models.TextField(help_text='Short-lived token for authenticating API requests.', verbose_name='Access Token')),
                ('refresh_token', models.TextField(help_text='Long-lived token to obtain a new access token without user interaction.', verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(help_text='The exact UTC datetime when the access token expires.', verbose_name='Token Expiry')),
                ('token_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Token Created At')),
                ('scopes', models.TextField(help_text='A space-delimited or JSON list of the permissions granted.', verbose_name='Granted Scopes')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to='accounts.coachprofile', verbose_name='Coach')),
            ],
            options={
                'verbose_name': 'Google Credentials',
                'verbose_name_plural': 'Google Credentials',
            },
        ),
    ]
