# Generated by Django 5.2.7 on 2025-11-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_is_client_and_more'),
        ('coaching_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOfferingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(help_text='Initial number of sessions purchased.', verbose_name='Total Sessions')),
                ('remaining_sessions', models.IntegerField(help_text='Number of sessions left for the client to book.', verbose_name='Remaining Sessions')),
                ('start_date', models.DateField(blank=True, help_text="The date of the client's first booked session.", null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='The calculated end date of the package based on the offering terms.', null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='True if the enrollment is current and has sessions remaining.', verbose_name='Is Active')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True, verbose_name='Enrolled On')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_enrollments', to='accounts.coachprofile', verbose_name='Assigned Coach')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='coaching_core.offering', verbose_name='Offering')),
            ],
            options={
                'verbose_name': 'Client Offering Enrollment',
                'verbose_name_plural': 'Client Offering Enrollments',
                'ordering': ['-enrolled_on'],
            },
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Time')),
                ('end_datetime', models.DateTimeField(verbose_name='End Time')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], default='BOOKED', max_length=20, verbose_name='Status')),
                ('gcal_event_id', models.CharField(blank=True, help_text='The unique ID for the event in Google Calendar.', max_length=255, null=True, verbose_name='Google Calendar Event ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.coachprofile', verbose_name='Coach')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='coaching_booking.clientofferingenrollment', verbose_name='Enrollment')),
            ],
            options={
                'verbose_name': 'Session Booking',
                'verbose_name_plural': 'Session Bookings',
                'ordering': ['start_datetime'],
                'unique_together': {('coach', 'start_datetime')},
            },
        ),
    ]
