# Generated by Django 5.2.7 on 2025-11-11 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_booking', '0002_alter_sessionbooking_enrollment_tastersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientofferingenrollment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='clientofferingenrollment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='clientofferingenrollment',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='The date when the enrollment expires.', null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='clientofferingenrollment',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 11, 8, 53, 0, 49050, tzinfo=datetime.timezone.utc), verbose_name='Purchase Date'),
            preserve_default=False,
        ),
    ]
