# Generated by Django 5.2.7 on 2025-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_booking', '0003_remove_clientofferingenrollment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Start Time'),
        ),
    ]
