# Generated by Django 5.2.7 on 2025-12-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_booking', '0004_alter_sessionbooking_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientofferingenrollment',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, help_text='The date and time when the enrollment became inactive (e.g., sessions ran out).', null=True, verbose_name='Deactivated On'),
        ),
    ]
