# Generated by Django 5.2.7 on 2025-12-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_booking', '0005_clientofferingenrollment_deactivated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='True if a reminder email has been sent for this session.', verbose_name='Reminder Sent'),
        ),
    ]
