# Generated by Django 5.2.7 on 2025-12-03 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_configure_social_app'),
        ('coaching_booking', '0006_sessionbooking_reminder_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneSessionFreeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_offered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Offered/Created')),
                ('redemption_deadline', models.DateTimeField(blank=True, help_text='The date by which the session must be booked AND scheduled.', null=True, verbose_name='Redemption Deadline')),
                ('is_approved', models.BooleanField(default=False, help_text='Must be approved by the coach before the client can book.', verbose_name='Coach Approved')),
                ('is_redeemed', models.BooleanField(default=False, help_text='Set to True once the session is successfully booked.', verbose_name='Is Redeemed')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_offers', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_free_offers', to='accounts.coachprofile', verbose_name='Assigned Coach')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_offer', to='coaching_booking.sessionbooking', verbose_name='Booked Session')),
            ],
            options={
                'verbose_name': 'One Session Free Offer',
                'verbose_name_plural': 'One Session Free Offers',
                'ordering': ['-date_offered'],
            },
        ),
    ]
