# Generated by Django 5.2.7 on 2025-12-10 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_stripe_customer_id'),
        ('coaching_booking', '0007_onesessionfreeoffer'),
        ('coaching_core', '0003_offering_coach_revenue_share_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Guest Email'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Guest Name'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='coaching_core.workshop', verbose_name='Workshop'),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.coachprofile', verbose_name='Coach'),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Awaiting Payment'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled')], default='BOOKED', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='CoachBusySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('source', models.CharField(default='GOOGLE_CALENDAR', max_length=50)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_slots', to='accounts.coachprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', 'start_time', 'end_time'], name='coaching_bo_coach_i_5001db_idx')],
            },
        ),
    ]
