# Generated by Django 5.2.7 on 2025-12-11 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_stripe_customer_id'),
        ('coaching_booking', '0008_sessionbooking_amount_paid_sessionbooking_created_at_and_more'),
        ('coaching_core', '0003_offering_coach_revenue_share_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionbooking',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sessionbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['BOOKED', 'PENDING_PAYMENT', 'COMPLETED'])), fields=('coach', 'start_datetime'), name='unique_active_coach_slot'),
        ),
    ]
