# Generated by Django 5.2.7 on 2025-12-13 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_stripe_customer_id'),
        ('coaching_booking', '0009_alter_sessionbooking_unique_together_and_more'),
        ('coaching_core', '0003_offering_coach_revenue_share_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionbooking',
            name='unique_active_coach_slot',
        ),
        migrations.AddConstraint(
            model_name='sessionbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['BOOKED', 'PENDING_PAYMENT', 'COMPLETED', 'RESCHEDULED'])), fields=('coach', 'start_datetime'), name='unique_active_coach_slot'),
        ),
    ]
