# Generated by Django 5.2.7 on 2025-12-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_booking', '0010_remove_sessionbooking_unique_active_coach_slot_and_more'),
        ('coaching_core', '0004_workshop_gcal_event_id_workshop_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='coaching_core.workshop', verbose_name='Workshop'),
        ),
    ]
