# Generated by Django 5.2.7 on 2025-12-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_booking', '0011_alter_sessionbooking_workshop'),
        ('coaching_core', '0004_workshop_gcal_event_id_workshop_meeting_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onesessionfreeoffer',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='onesessionfreeoffer',
            name='is_redeemed',
        ),
        migrations.AddField(
            model_name='onesessionfreeoffer',
            name='offering',
            field=models.ForeignKey(blank=True, help_text='The specific offering this taster is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taster_offers', to='coaching_core.offering'),
        ),
        migrations.AddField(
            model_name='onesessionfreeoffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('USED', 'Used')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='offering',
            field=models.ForeignKey(blank=True, help_text='Used for one-off bookings like taster sessions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taster_bookings', to='coaching_core.offering'),
        ),
    ]
