# Generated by Django 5.2.7 on 2025-12-22 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_guest_alter_user_email'),
        ('coaching_booking', '0012_remove_onesessionfreeoffer_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='is_coverage_session',
            field=models.BooleanField(default=False, help_text='True if this session is being covered by a coach other than the primary enrollment coach.'),
        ),
        migrations.AlterField(
            model_name='clientofferingenrollment',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_client_enrollments', to='accounts.coachprofile', verbose_name='Primary Coach'),
        ),
        migrations.AlterField(
            model_name='clientofferingenrollment',
            name='deactivated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deactivated On'),
        ),
        migrations.AlterField(
            model_name='clientofferingenrollment',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='clientofferingenrollment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='clientofferingenrollment',
            name='remaining_sessions',
            field=models.IntegerField(verbose_name='Remaining Sessions'),
        ),
        migrations.AlterField(
            model_name='clientofferingenrollment',
            name='total_sessions',
            field=models.IntegerField(verbose_name='Total Sessions'),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_bookings', to='accounts.coachprofile', verbose_name='Session Provider'),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='gcal_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Calendar Event ID'),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessionCoverageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Notes for the covering coach.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requesting_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_coverage_requests', to='accounts.coachprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_requests', to='coaching_booking.sessionbooking')),
                ('target_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_coverage_requests', to='accounts.coachprofile')),
            ],
            options={
                'verbose_name': 'Session Coverage Request',
                'verbose_name_plural': 'Session Coverage Requests',
            },
        ),
    ]
