# Generated by Django 5.2.7 on 2025-12-29 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_guest_alter_user_email'),
        ('coaching_booking', '0013_sessionbooking_is_coverage_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='attendance',
            field=models.CharField(choices=[('PENDING', 'Not Yet Marked'), ('ATTENDED', 'Attended'), ('NOSHOW', 'No-Show'), ('PARTIAL', 'Partial Participation')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='coach_private_notes',
            field=models.TextField(blank=True, help_text='Private notes about client engagement (not shown to client).'),
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_rating', models.PositiveSmallIntegerField(default=5)),
                ('delivery_rating', models.PositiveSmallIntegerField(default=5)),
                ('value_rating', models.PositiveSmallIntegerField(default=5)),
                ('results_rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True, help_text='Public feedback about the experience.')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('PENDING_STAFF', 'Awaiting Staff Review'), ('REJECTED', 'Rejected')], default='PUBLISHED', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes for review disputes.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.coachprofile')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='coaching_booking.clientofferingenrollment')),
            ],
            options={
                'verbose_name': 'Coach Review',
                'verbose_name_plural': 'Coach Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
