# Generated by Django 5.2.7 on 2025-12-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching_booking', '0014_sessionbooking_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientofferingenrollment',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed On'),
        ),
    ]
