# Generated by Django 5.2.7 on 2026-01-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0016_alter_variant_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name e.g. 'GUILD MEMBER'", max_length=100)),
                ('slug', models.SlugField(help_text="Used for HTML IDs, e.g. 'guild_member'", max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many units of the variant are included?')),
                ('css_class', models.CharField(default='LONE_WOLF', help_text="CSS class for styling hooks, e.g. 'LONE_WOLF', 'RAID_LEADER'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which tiers appear (lowest first)')),
                ('is_active', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_tiers', to='products.variant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TierPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="The perk text, e.g. 'Signed & Numbered'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perks', to='awakening.funneltier')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
