# Generated by Django 5.2.7 on 2026-01-15 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awakening', '0001_initial'),
        ('coaching_core', '0005_alter_offering_coaches'),
        ('products', '0016_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierperk',
            name='link_url',
            field=models.URLField(blank=True, help_text='Optional: A URL for this perk, e.g., a link to a WhatsApp group.', null=True),
        ),
        migrations.AddField(
            model_name='tierperk',
            name='linked_offering',
            field=models.ForeignKey(blank=True, help_text='Optional: Link this perk to a specific coaching offering to grant access.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaching_core.offering'),
        ),
        migrations.CreateModel(
            name='OrderBump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name for this offer, e.g., 'Audiobook Bump'", max_length=100)),
                ('headline', models.CharField(help_text="The catchy headline above the choice, e.g., 'Final Offer: Upgrade Your Order!'", max_length=255)),
                ('is_default_choice', models.BooleanField(default=False, help_text='Check this for the offer you want to be pre-selected by default.')),
                ('is_active', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(help_text='The product variant that will be added to the order.', on_delete=django.db.models.deletion.CASCADE, to='products.variant')),
            ],
        ),
    ]
