# Generated by Django 5.2.7 on 2026-01-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awakening', '0002_tierperk_link_url_tierperk_linked_offering_orderbump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funneltier',
            name='css_class',
            field=models.CharField(choices=[('party-leader', 'Party Leader (Green)'), ('guild-member', 'Guild Member (Blue)'), ('raid-leader', 'Raid Leader (Purple/Gold)')], default='party-leader', help_text='Select the visual style for this tier on the offers page.', max_length=50, verbose_name='CSS Style Class'),
        ),
    ]
