# Generated by Django 5.2.7 on 2025-10-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted')], default='open', max_length=10),
        ),
    ]
