# Generated by Django 5.2.7 on 2025-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='abandoned_cart_sent',
            field=models.BooleanField(default=False, help_text='True if an abandoned cart reminder has been sent for this cart.'),
        ),
    ]
