# Generated by Django 5.2.7 on 2025-10-29 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variant_color_variant_size_alter_variant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'White T-Shirt Blanks', 'Coaching Slot Quota'", max_length=100, unique=True)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'color', 'size')},
        ),
        migrations.AddField(
            model_name='variant',
            name='stock_pool',
            field=models.ForeignKey(blank=True, help_text='Select the shared pool of inventory this variant uses.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stockpool'),
        ),
        migrations.RemoveField(
            model_name='variant',
            name='inventory',
        ),
    ]
