# Generated by Django 5.2.7 on 2025-10-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stockpool_alter_variant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
