# Generated by Django 5.2.7 on 2025-11-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockpool',
            name='name',
            field=models.CharField(help_text="e.g., 'White T-Shirt Blanks'", max_length=100, unique=True),
        ),
    ]
