# Generated by Django 5.2.7 on 2025-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='printful_product_id',
            field=models.CharField(blank=True, help_text='ID from Printful Sync Product', max_length=255, null=True),
        ),
    ]
