# Generated by Django 5.2.7 on 2025-12-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_printful_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in grams (g). Required for self-fulfilled shipping calculation.', max_digits=8),
        ),
    ]
