# Generated by Django 5.2.7 on 2025-12-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fulfillment_method',
            field=models.CharField(choices=[('digital', 'Digital / None'), ('printful', 'Printful (Drop Shipping)'), ('local', 'Local Stock (Royal Mail)')], default='local', help_text='Who is responsible for shipping this item?', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital'), ('service', 'Service/Coaching')], default='physical', max_length=20),
        ),
    ]
