# Generated by Django 5.2.7 on 2025-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_fulfillment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fulfillment_method',
            field=models.CharField(choices=[('printful', 'Printful (Drop Shipping)'), ('local', 'Local / Royal Mail'), ('digital', 'Digital / Instant')], default='local', help_text='Who ships this? Printful uses flat rates; Local uses weight.', max_length=20),
        ),
    ]
