# Generated by Django 5.2.7 on 2025-12-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_fulfillment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_category',
            field=models.CharField(choices=[('default', 'Default / Standard'), ('t-shirt', 'T-Shirt / Top'), ('hoodie', 'Hoodie / Sweatshirt'), ('jacket', 'Jacket'), ('pant', 'Pants / Joggers'), ('bag', 'Bag / Backpack'), ('hat', 'Hat / Beanie'), ('mug', 'Mug / Drinkware'), ('poster', 'Poster / Canvas'), ('sticker', 'Sticker')], default='default', help_text='Used to calculate manual shipping rates.', max_length=20),
        ),
    ]
