# Generated by Django 5.2.7 on 2026-01-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_shipping_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dice_rating',
            field=models.PositiveIntegerField(default=0, help_text='Enter a rating (e.g., 1-5) to be displayed as dice icons.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(default=False, help_text='Check this box if the product is currently in preorder status.'),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_release_date',
            field=models.DateField(blank=True, help_text='The expected date this product will be released or shipped.', null=True),
        ),
    ]
