# Generated by Django 5.2.7 on 2026-01-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_dice_rating_product_is_preorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_category',
            field=models.CharField(choices=[('default', 'Default / Standard'), ('t-shirt', 'T-Shirt / Top'), ('hoodie', 'Hoodie / Sweatshirt'), ('jacket', 'Jacket'), ('pant', 'Pants / Joggers'), ('bag', 'Bag / Backpack'), ('hat', 'Hat / Beanie'), ('mug', 'Mug / Drinkware'), ('poster', 'Poster / Canvas'), ('sticker', 'Sticker'), ('book', 'Book / Literature')], default='default', help_text='Used to calculate manual shipping rates.', max_length=20),
        ),
    ]
