# Generated by Django 5.2.7 on 2026-01-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_shipping_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_included',
            field=models.BooleanField(default=False, help_text='If checked, this product ships free (not counted in shipping calc).'),
        ),
    ]
