# Generated by Django 5.2.7 on 2026-01-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_shipping_included'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'color', 'size', 'name')},
        ),
    ]
